### ISSUE TITLE
cli always segfaults on linux

### ISSUE THREAD

**Issue by ChristophHaag** [maluoi/openxr-explorer#3]
gui works fine, but when giving an argument to invoke the cli, there is always a segfault
```
gdb -q --args build/openxr-explorer help
Reading symbols from build/openxr-explorer...
(gdb) r
Starting program: /home/haagch-collabora/openxr-explorer-git/src/openxr-explorer/build/openxr-explorer help
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bd42ca in glXCreateContext () from /usr/lib/libGLX.so.0
(gdb) bt
#0  0x00007ffff7bd42ca in glXCreateContext () from /usr/lib/libGLX.so.0
#1  0x00005555555cd2bf in gl_init_glx () at /home/haagch-collabora/openxr-explorer-git/src/openxr-explorer/src/openxrexplorer/imgui/sk_gpu.h:2503
#2  0x00005555555cd409 in skg_init (app_name=app_name@entry=0x555555607184 "OpenXR Explorer", adapter_id=adapter_id@entry=0x0) at /home/haagch-collabora/openxr-explorer-git/src/openxr-explorer/src/openxrexplorer/imgui/sk_gpu.h:2549
#3  0x000055555556372d in app_cli (arg_count=2, args=0x7fffffffd978) at /home/haagch-collabora/openxr-explorer-git/src/openxr-explorer/src/openxrexplorer/app_cli.cpp:31
#4  0x000055555555a559 in app_args (arg_count=<optimized out>, args=<optimized out>) at /home/haagch-collabora/openxr-explorer-git/src/openxr-explorer/src/openxrexplorer/main.cpp:35
#5  0x000055555555a38a in main (arg_count=<optimized out>, args=<optimized out>) at /home/haagch-collabora/openxr-explorer-git/src/openxr-explorer/src/openxrexplorer/imgui/imgui_skg.cpp:41
```

**Comment by maluoi** [comment]
I'll be looking into this right after I resolve the cmake issues!
